apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-orlg
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-ighj-tenant/rhtap-demo-app/hacbs-test-project-orlg@sha256:3069c8a9c615a43e739ca6aec8e85c192a83e5e9129138351fb5f1625bbcbc32
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
